### ISSUE TITLE
Upgrade Plan

### ISSUE THREAD

**Issue by devnore** [kwent/syno#18]
Are you planing on upgrading the package to fix the api-changes that where made with dsm 6 release?

**Comment by kwent** [comment]
@devnore Do you have an idea of what is broken of what api you would like to add ?

**Comment by kwent** [comment]
Actually i know what changed. I will release a `2.0` version soon which will support `DSM 5.2` and `DSM 6.0`

**Comment by devnore** [comment]
Wonderful, have not had the time to answer your question.

Seams like default entrypoint is entry.cgi

and another thing seams to be that some arguments have changed.

example 
SYNO.FileStation.CreateFolder
method: create
parameter: Name

> One or more new folder names, separated by commas “,” **and around brackets**. The number of
> names must be the same as the number of folder paths in the folder_path parameter. The first
> name parameter corresponding to the first folder_path parameter.

**Comment by davidmatas** [comment]
Any news here? Do you need help?

**Comment by kwent** [comment]
Sorry guys, i began a `2.0` branch here https://github.com/kwent/syno/commits/2.0.

Did not had time to polish and release a new version yet. But that should already work with DSM 6.0.

Will try to finish, polish and release asap.

BTW. If you guys are on DSM 5.2 still let me know, i need your help for some api files i need to get. (cc @devnore @davidmatas )

**Comment by davidmatas** [comment]
I jumped to DSM 6.0 a few weeks ago, sorry :(

**Comment by davidmatas** [comment]
@kwent I'm having problems with the 2.0 branch:
1. The path to `definitions/" + this.apiVersion + "/compiled/full.json` is not available. It works using `fs.readFileSync(path.join(__dirname, "../definitions/" + this.apiVersion + "/compiled/full.json"), 'utf8'))`

```
Error: ENOENT: no such file or directory, open 'definitions/6.0/compiled/full.json'
    at Error (native)
```
1. I am using `syno.fs.download` but it doesn't work with new API. I'm getting the following error:

```
/node_modules/syno/dist/syno.js:78
                        code = body.error ? body.error.code : body.data[0].error;
                                                                       ^
TypeError: Cannot read property '0' of undefined
```

I'm trying to download photograps and when inspect the response/body I see the binary data, so I think it is fine but the file stores empty

**Comment by kwent** [comment]
@davidmatas Nevermind 2.0 is probably broken and still need to be finished. It's taking a long time cause i redid all the engine and it's a lot of changes to support all api versions.

**Comment by davidmatas** [comment]
Great! just wanted provide some weird things I've seen. Thanks for your work

**Comment by kwent** [comment]
@davidmatas I just released a new `2.0.0` version which support `5.x` and `6.x`version ! Give it a shot !

**Comment by davidmatas** [comment]
@kwent The problem with `syno.fs.download` continues.

```
/node_modules/syno/dist/syno.js:78
                        code = body.error ? body.error.code : body.data[0].error;
                                                                       ^
TypeError: Cannot read property '0' of undefined
```

Maybe the writable stream needed for download is not been managed correctly? If I inspect the body I see all the binary data

**Comment by kwent** [comment]
@davidmatas Do you use the CLI or the JS API directly ?

**Comment by davidmatas** [comment]
The JS api. 

```
syno.fs.download({
  path: file,
  stream: fs.createWriteStream(year + '/' + path.basename(file)),
  mode: 'open'
}, function(err, data){
  console.log(err, data);
});
```

**Comment by kwent** [comment]
Oh nice. yeah `stream` are not supported for now. I need to find a clean way to detect you passed a stream in the parameters.

**Comment by davidmatas** [comment]
So is there any way to get work `fs.download` for now?

**Comment by kwent** [comment]
Not really. I will try to do a minor update soon to support it.

**Comment by davidmatas** [comment]
Any news about the `stream` support?

**Comment by davidmatas** [comment]
@kwent ping

**Comment by kwent** [comment]
Hi @davidmatas.

Well i haven't had the time to implements `stream` support. PR is highly encouraged.
