### ISSUE TITLE
Your documentation seems incomplete

### ISSUE THREAD

**Issue by jonathanroze** [kwent/syno#23]
Hi, 

First of all, thank you for you work ! 

But i have a question, on your readme you have write a method to get file :
-  syno.fs.list({'folder_path':'/path'}, callback);

but on this page : https://github.com/kwent/syno/wiki/Download-Station-API
The method is not set ! it is not clear and i don't understand your documentation, so if you have some explanations for me :) ! 

Thanks you

**Comment by kwent** [comment]
Hi @Clowning.

Yes the wiki is not up to date and i should probably remove it to avoid any confusion.

You should refer to the synology documentation (Cf. https://www.synology.com/en-us/support/developer#tool). The main issue is that the documentation Synology side is very poor or sometimes just does not exists for some packages.

By the way `fs` is for `FileStation` (and not `DownloadStation` as you refer) so you should take a look at the `FileStation` documentation available here: https://global.download.synology.com/download/Document/DeveloperGuide/Synology_File_Station_API_Guide.pdf

Regards
